### ISSUE TITLE
As  developer I wanted to use the CLI library to parsing arguments.

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#1]
Acceptance criteria 
- Parsing the command line input directly to CLI without args
- The code still being readable
- Higher cohesion
- Using the library without external parsers 

Advanteges 
- Command line is problematic
- Readability 
- requirement for course

**Comment by Lukan707** [comment]
The code have now been refactored to use the CommandLineParser library. All changes have been merged to main and development branch, and the branch used have been deleted.

The implementation meets the criteria of this issue, as well as the requirements of the project work description from week 36 of the course.

The CommandLineParser have been choosen because:
- it has no dependencies, 
- is stable, feature complete, and have a high versionnumber (many iterations)
- is popular and have millions of downloads
