### ISSUE TITLE
Cheep text and Author name and email can't be empty strings

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#101]
## User story
The string fields cheep.text, author.name and author.name can be empty in the migrations table. They cannot be null, and has a max length, but the empty fields needs to be made.

## Precise description of what to do and evt. time estimate
Fix so they cant be empty, for the email field, it might be optimal to have it contain a @, since all emails should contain this.
The best place to work with this would be in the context class, in the method onModelCreation.

## Acceptance criteria (testeable)
- [x] Not testable, but in the migrations table it shouldn't be empty
- [x] Making an author with an empty name should not be possible
- [ ] Making an author with an empty email, that doesn't contain @ should not be possible

**Comment by Lukan707** [comment]
Empty strings can be disallowed witth the required attribute with the AllowEmptyStrings boolean option set to false.
https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute.allowemptystrings?view=net-7.0

**Comment by Lukan707** [comment]
Data annotions are added to the two fields Name and Email in AuthorDTO.
Be aware that calling the method .IsRequired form the fluent API, on the theese two fields in the override of the OnModelCreating method, now may overwrite the data annotations, since using the fluent API is the strongest form of configuration:
https://learn.microsoft.com/en-us/ef/core/modeling/#:~:text=configure%20a%20model-,You,-can%20override%20the

**Comment by Lukan707** [comment]
For testing a new author is not added with an empty string as name or email, it is asserted that the return result of the savechanges method is 0, since savechanges returns the number of writes to the database:
https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext.savechanges?view=entity-framework-6.2.0&redirectedfrom=MSDN#overloads:~:text=The%20number%20of%20state%20entries%20written%20to%20the%20underlying%20database.

**Comment by annahj1006** [comment]
Closed with branch
