### ISSUE TITLE
As a developer I want to test the pageination of the Razor implementation

### ISSUE THREAD

**Issue by Faberen** [ITU-BDSA23-GROUP4/Chirp#37]
Acceptance Criteria

- Test that the number of pages matches the numer of Cheeps IE that if a user has 66 cheeps there should be 3 pages
- Test that there is 32 Cheeps on a standard page

**Comment by Lukan707** [comment]
This should be done using API testing

**Comment by Lukan707** [comment]
This seems to be implemented on pull request #52 

However the first acceptance criteria "Test that the number of pages matches the number of Cheeps IE that if a user has 66 cheeps there should be 3 pages".

Consider to either delete/change the test criterias to match the testsuites of pull request #52 , and close this issues, when the pull request is accepted and merged into main. This seems to be okay, since the code and choosen implementation has changed a lot, since the acceptance criterias were written.

Or, add a test suite to test the above mentioned acceptance criteria, create a pull request and merge it into main, and close this issues when that new pull request, have been accepted and merged into main.

**Comment by Lukan707** [comment]
Together with @Faberen is have been decided to not test for the acceptance criteria "Test the number of pages matches the number of Cheeps IE that if a user has 66 cheeps there should be 3 pages". As this will be a very complicated affair to test for, in the current state of the code, and is partially covered by other unit and integrations, which test for the number of cheeps per page, and if the content of different pages i different.
