### ISSUE TITLE
Resctrict the length of cheeps

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#66]
Make sure that your database does not contain cheeps, whose text is longer than 160 characters. Implement this restriction by constraining the data model accordingly. Implement other reasonable restrictions on author name length etc.

# Edit 

## Description
Cheeps need to be restricted so that each cheep message is less than 160 characters long. 
there needs to be a check for all layers of the code 

## Acceptance Criteria 
- [x] Write a OnModelCreation method that restricts the length of cheeps
- [x] Check that writing a cheep that is 161+ characters long throws an exception
- [x] Check that we can write a cheep that is exactly 160 characters long 
- [x] Check that we can write a cheep that is under 160 characters long 
- [x] Check that we cannot write a cheep that is 0 characters long and that it throws a fitting exception 
- All these tests need to be implemented for all layers Ei: DB, Infrastructure, and views

**Comment by AlbinoLoaf** [comment]
For the issues, there are lack of a description and acceptance criteria

## Description
Cheeps need to be restricted so that each cheep message is less than 160 characters long. 
there needs to be a check for all layers of the code 


## Acceptance Criteria 
- Check that writing a cheep that is 161+ characters long throws an exception
- Check that we can write a cheep that is 160 characters long 
- Check that we can write a cheep that is 80 characters long 
- Check that we cannot write a cheep that is 0 characters long and that it throws a fitting exception 
- All these tests need to be implemented for all layers Ei: DB, Infrastructure, and views
